export const env = {
NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL!,
STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET!,
STRIPE_PRICE_MONTHLY_299: process.env.STRIPE_PRICE_MONTHLY_299!, // £2.99/mo
};
